name: Nuestro Workflow

on:
  workflow_call:
    inputs:
      types:
       required: true
       type: string
         mensaje:
           required: true
           type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/reutilizable.yml

      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.node }}"
